### ISSUE TITLE
Gemsmith says "update available" when latest (v1.8 for 1.0.20a) is installed.

### ISSUE THREAD

**Issue by LoganAvatar** [gemforce-team/gemsmith#1]
Installed bezelmodloader and gemsmith, image shows an "Update available!" text at the bottom of the box

![image](https://user-images.githubusercontent.com/7676429/74615207-6a4d6500-50d3-11ea-8e8e-08c0124ab672.png)

**Comment by hellrage** [comment]
Thanks for reporting it, fixed in v1.9!
